FROM adoptopenjdk/openjdk11

WORKDIR /usr/app

COPY target/*.jar /usr/app/

ARG value

ENV envValue=$value

#RUN ls -lrt calculator-api-${envValue}.jar

#ENTRYPOINT ["java","-jar","calculator-api-${envValue}.jar"]
CMD java -jar -Dserver.port=$PORT calculator-api-${envValue}.jar
